import pandas as pd

# Example data structure for the extracted Q&A
data = {
    'Question': [
        " What are the causes of Vata aggravation?",
        " What is the role of ashwagandha in Vata treatment?",
        " How does Ayurveda treat Pitta problems?",
        " What are common Ayurvedic herbs used for Kapha problems?",
        " What herbs are used to enhance immunity in Ayurveda?",
        " What is the role of digestive fire (Agni) in Ayurveda?",
        " How does Ayurveda classify diarrhea?",
        " What is the Ayurvedic treatment for indigestion (Ajirna)?",
        " What is the role of triphala in Ayurvedic treatments?",
        " How is Pitta-aggravated diarrhea treated in Ayurveda?",
        " What are some Ayurvedic herbs to support the immune system and reduce inflammation?",
        " How does Ayurveda classify rasayanas for physical and mental well-being?",
        " What herbs are suggested for weak digestion in children according to Ayurveda?",
        " What is the significance of ghee in Ayurvedic treatments?",
        " What are the main strategies for treating digestive issues like low Agni in Ayurveda?",
        " How is Shatavari used in Ayurveda for digestive problems?",
        " What is the Ayurvedic treatment for excess Kapha?",
        " What is a rasayana, and what are its benefits in Ayurveda?",
        " How does Ayurveda explain the role of Triphala in treating digestive issues?",
        " What are the Ayurvedic herbs recommended for treating inflammation?",
        " What are the characteristics of Vata-aggravated diarrhea according to Ayurveda?",
        " What is the role of Shatavari in Ayurvedic treatments?",
        " How does Ayurveda classify the six tastes (Rasa)?",
        " What are the causes of diarrhea according to Ayurveda?",
        " What herbs are used in Ayurveda for treating Kapha problems?",
        " What is the Ayurvedic understanding of the pathogenesis of diarrhea?",
        " What is Rasayana therapy in Ayurveda?",
        " How is pitta-aggravated diarrhea described in Ayurveda?",
        " What is the role of Amalaki in treating digestive problems in children?",
        " What is dysentery, according to Ayurveda?",
        " What are the main clinical features of diarrhea in Ayurveda?",
        " What are some Ayurvedic treatments for emotional diarrhea?",
        " What is Ama Atisara in Ayurveda?",
        " How does Ayurveda define Pitta-type diarrhea?",
" What herbs are recommended for Vata problems in children?",
" What is the significance of rasayana therapy in Ayurveda?",
" How does Ayurveda treat Kapha-type diarrhea?",
" What are the common causes of Pitta aggravation in children?",
" How is Shatavari used in Ayurveda for digestive issues?",
" What are the Ayurvedic principles for treating Pitta imbalances?",
" What are the benefits of sesame oil in Ayurveda?",
" What are some Ayurvedic treatments for emotional diarrhea?",
" How is Triphala used to reduce excess Pachaka Pitta?",
" What herbs are used for balancing Vata and Kapha doshas in children?",
" What is the role of amalaki in Ayurvedic therapies?",
" What are the benefits of using guduchi in Ayurveda?",
" How is the digestion fire (Agni) treated in Ayurveda?",
" What is the role of nasya (nasal administration of oils) in treating Vata problems?",
" What herbs are commonly used for inflammation in Ayurveda?",
" What are the key components of rasayana therapy for improving mental health?",
" What are the best herbs for strengthening immunity in children according to Ayurveda?",
" How does cinnamon contribute to immune health in Ayurveda?",
" What is the Ayurvedic treatment for constipation in children?",
" What role does sesame oil play in Ayurveda?",
" What is the significance of ginger in Ayurvedic medicine?",
" What is the Ayurvedic approach to treating respiratory infections in children?",
" How is amalaki used for treating digestive disorders in Ayurveda?",
" What is the role of Triphala in treating Pitta imbalances?",
" How does Ayurveda treat diarrhea in children?",
" What herbs are recommended for mental health in Ayurveda?",
" What Ayurvedic herbs are used for treating respiratory infections in children?",
" How does Ayurveda view mental illness in terms of trigunas?",
" What Ayurvedic herbs are used to boost memory and cognitive function?",
" What is the Ayurvedic approach to treating digestive problems in children?",
" What is Brahmi and how is it used in Ayurveda?",
" How does liquorice support immunity in Ayurveda?",
" What are the benefits of gotu kola for mental health in children?",
" How does Ayurveda treat hay fever in children?",
" What herbs are recommended for low digestive fire (Agni Manda) in Ayurveda?",
" What is the role of Triphala in Ayurvedic pediatric care?",
" What are the Ayurvedic herbs that boost the immune system in children?",
" How is liquorice used to support respiratory health in Ayurveda?",
" What Ayurvedic herbs are recommended for treating Kapha-related respiratory issues?",
" What is the role of Trikatu in Ayurveda?",
" How does Brahmi help cognitive function in children?",
" What are the benefits of Shatavari in treating digestive issues in children?",
" How is ashwagandha used in Ayurveda for mental health?",
" What herbs are used to treat recurrent respiratory infections in children?",
" How does Ayurveda treat digestive issues caused by low Agni in children?",
" What is the Ayurvedic approach to treating ADHD in children?",
" How does Ayurveda approach the treatment of ADHD in children?",
" What herbs are recommended for treating respiratory infections in children?",
" How is low digestive fire (Agni Manda) treated in Ayurveda?",
" What is the role of Triphala in treating indigestion in children?",
" How does Ayurveda view anxiety disorders and their treatment?",
" How is Brahmi used for cognitive function in Ayurveda?",
" What are the symptoms of low digestive fire (Agni) in children according to Ayurveda?",
" What herbs are used for mental health disorders in Ayurveda?",
" What is the role of ginger in treating digestive disorders in children?",
" How does Ayurveda treat cognitive development issues in children?",
" What are the recommended herbs for boosting memory in children according to Ayurveda?",
" How does Ayurveda treat anxiety in children?",
" What herbs are recommended for treating indigestion in children?",
" What are the effects of Brahmi on cognitive function?",
" What Ayurvedic herbs are used to treat respiratory health in children?",
" What is the role of Triphala in Ayurvedic treatments for indigestion?",
" How does Jatamansi help in treating mental health issues in Ayurveda?",
" How does ginger help in treating respiratory infections?",
" What is the Ayurvedic approach to improving cognitive function in children?",
" What is the role of Gotu Kola in pediatric care according to Ayurveda? -",
        
        
    ],
    'Answer': [
        "Atisara in Sanskrit means frequent passing of excessively watery, unformed stool.",
        "The six tastes in Ayurveda are sweet, sour, salty, pungent, bitter, and astringent.",
        "Common causes of diarrhea in Ayurveda include the consumption of excessive food that is hard to digest, dry foods, and contaminated water.",
        "Herbs contraindicated in children include Aconitum spp., Adonis vernalis, Aristolochia spp., and others.",
        "Post Digestive Effect, or Vipaka, occurs after digestion when nutrients are assimilated deep within the tissues.",
        "Conventional medicine classifies diarrhea into four types acute bloody diarrhea, acute watery diarrhea, persistent diarrhea, and diarrhea with severe malnutrition.",
        "Ayurveda recommends that a child with a Pitta constitution should drink water after meals to avoid stomach burning and other Pitta disorders.",
        "Rasayana formulas like ashwagandha and tulsi help improve psychological symptoms in elderly individuals, attributed to their antistress and adaptogenic properties."
    ],
    'Source':[
        
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Save to a CSV file
#df.to_csv('questions_answers.csv', index=False)
